### ISSUE TITLE
error when adding pid-is-include rules

### ISSUE THREAD

**Issue by xrkk** [eronnen/procmon-parser#10]
Adding pid-is-include rules through `Rule('pid', 'is', str(pid), 'include')` will have no effect.
The rule item does appears in the procmon filter view, but it just have no effect.
Manually adding pid-is-include rule and export configuration and diff with previous one, there is a small difference: the manually added pmc file have two bytes of pid integer, and the corresponding two bytes in previsou one is just zero.
Please check it out.

**Comment by eronnen** [comment]
It seems that for integer values they store both the value as a string and as an integer. Thanks for the bug report!
