### ISSUE TITLE
Show when files are deleted

### ISSUE THREAD

**Issue by wootski** [eronnen/procmon-parser#17]
Hi @eronnen,

I was wondering if it would be possible to parse the PML file and show when a file is being deleted for _SetDispositionInformationFile_ and _SetDispositionInformationEx_ operations. When a file is deleted, ProcMon shows “Delete: True” in the _Detail_ column.

I attempted to locate where the Detail value (True/False) could be stored by looking at both [read_event](https://github.com/eronnen/procmon-parser/blob/48f7ff944281acd52d4466121f47605ae5bc3950/procmon_parser/stream_logs_format.py#L181) and [get_filesystem_event_details](https://github.com/eronnen/procmon-parser/blob/48f7ff944281acd52d4466121f47605ae5bc3950/procmon_parser/stream_logs_detail_format.py#L576), however I was unsuccessful in identifying common values between these events in the test PML files I generated. Do you have any ideas on how it may be storing this information?

**Comment by eronnen** [comment]
probably the easiest way to find out is to look at two events with "Delete: True" and "Delete: False" and compare them. Do you have a PML with these events? I can take a look.

**Comment by wootski** [comment]
I have attached a PML file which only contains two _SetDispositionInformationFile_ events for both cases (True/False), I used an older version of ProcMon as I did this in a test virtual machine, hopefully there were no recent updates to the file format.

[delete_file.zip](https://github.com/eronnen/procmon-parser/files/6505832/delete_file.zip)

**Comment by eronnen** [comment]
it seems that this PML's version is too old for the parser... the parser handles version 9 and this file's version is 7. I think you can still use newer versions of Procmon on old machines, anything above 3.4.0 should be enough.

**Comment by wootski** [comment]
I've updated the sample PML above.

**Comment by eronnen** [comment]
seems it is the case, i added a small PR to support that:

https://github.com/eronnen/procmon-parser/pull/18/files

**Comment by wootski** [comment]
Yeah that looks change looks good, thank you for adding that in! :)
