### ISSUE TITLE
Is it possible to extract network connection IP information of each PID?

### ISSUE THREAD

**Issue by 040840308** [eronnen/procmon-parser#20]
Hi, everyone
      I wonder whether procmon can be used to extract the network connection information of each process, such as IP, etc.

     Thanks

**Comment by eronnen** [comment]
Procmon shows TCP/UDP events and their PROCESS:

![image](https://user-images.githubusercontent.com/63298684/129253477-87e30bb7-38b1-4b14-bd18-32e9abcff972.png)
