### ISSUE TITLE
Is there a way to collect the real-time network speed of each process and the total traffic of each process

### ISSUE THREAD

**Issue by LRF520** [eronnen/procmon-parser#21]
Is there a way to collect the real-time network speed of each process and the total traffic of each process ?

**Comment by eronnen** [comment]
Procmon doesn't provides network speed information, maybe you could estimate it by time differences between send and receive events, and you can calculate the total bytes traffic per process by summing up the `Length` field in all of the network events `detail` field

**Comment by LRF520** [comment]
Thanks a lot , i will try it .
