### ISSUE TITLE
load_configuration or loads_configuration

### ISSUE THREAD

**Issue by xrkk** [eronnen/procmon-parser#8]
I tested both on Python2.7 and Python3.8, used sample code in Readme.md:
`config = loads_configuration(f.read())` works fine, but `config = load_configuration(f.read())` returns empty dict.
Please check it out.

**Comment by eronnen** [comment]
Yes, the readme is wrong... It's supposed to be like the json api, `loads` gets bytes object and `load` gets a file-like object. I'll fix the readme soon :)
